### ISSUE TITLE
Add __eq__ method so container objects can be easily compared

### ISSUE THREAD

**Issue by zduey** [pennmem/classiflib#3]
It would be very helpful for regression testing and possibly other use cases to be able to check that two container objects are equal. I believe we just need to implement an __eq__ method, which I think should just check that the properties of the given object and the current object have the same values

**Comment by mivade** [comment]
Do we want to verify that everything matches exactly? Or do we want some sort of tolerance? Some things also shouldn't be checked (such as version numbers and probably ROC curve data since that's not always populated).

**Comment by zduey** [comment]
I don't think everything needs to be an exact match, but there are certainly a subset of properties that should not change
